# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install meson
        run: |
          pip3 install --user meson

      - name: update path
        run: echo "C:\\Users\\runneradmin\\AppData\\Roaming\\Python\\Python37\\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: show path
        run: echo $env:path
          

      # Runs a set of commands using the runners shell
      #- name: checkout postgresql
      #  run: |
      #    git clone --depth=1 https://github.com/postgres/postgres.git
      #    pushd postgres
      #    meson configure build
      #    cd build
      #    ninja
